apiVersion: v1
kind: Service
metadata:
  name: {{ include "distcc.fullname" . }}
spec:
  externalTrafficPolicy: {{ .Values.externalTrafficPolicy }}
  selector:
    app: distcc
  type: NodePort
  ports:
    - name: distcc
      protocol: TCP
      port: 3632
      targetPort: 3632
      nodePort: {{ .Values.service.statsPort }}
    - name: distcc-stats
      protocol: TCP
      port: 3632
      targetPort: 3632
      nodePort: {{ .Values.service.statsPort }}
